(use ../libmpsse)

(let [[l d] (ft/version)]
      (printf "libMPSSE Version: %d.%d.%d" ;l)
      (printf "ftd2xx Version: %d.%d.%d\n" ;d))
(assert (= :ok (i2c/err)) (i2c/err))

# I2C
(def chans (i2c/channels))
(assert (= :ok (i2c/err)) (i2c/err))
(print "I2C channels found: " chans)
(when (pos? chans)
    (print "Opening I2C channel #1...")
    (with [c (i2c/open 1)]
          (pp c)
          (assert (= :ok (:err c)) (i2c/err))
          (assert (not (nil? c)))
          (assert (:is-open c))
          (var ci (i2c/info c))
          (assert (struct? ci))
          (assert (not (nil? (i2c/find-by :id (get ci :id)))))
          (assert (not (nil? (i2c/find-by :serial (get ci :serial)))))
          (assert (nil? (i2c/find-by :serial "nope")))
          (eachp [k v] ci
            (print k ":"
                   (string/repeat " " (- 13 (length k)))
                   (if (number? v)
                     (string/format "0x%X" v)
                     v)))
          (assert (:close c))
          (assert (= :ok (:err c)))
          (assert (not (:is-open c)))
          (print "I2C channel successfully closed.\n")))

# SPI
(def chans (spi/channels))
(assert (= :ok (spi/err)) (spi/err))
(print "SPI channels found: " chans)
(when (pos? chans)
    (print "Opening SPI channel #1...")
    (with [c (spi/open 1)]
          (pp c)
          (assert (= :ok (:err c)) (spi/err))
          (assert (not (nil? c)))
          (assert (:is-open c))
          (def pins (spi/pins c [0xAA 0xBB] [0xCC 0xDD]))
          (assert (= pins 0xDDCCBBAA) (errorf "expected 0x%X from (spi/pins) but got: 0x%X" 0xDDCCBBAA pins))
          (spi/pins c [0 0] [0 0])

          (prin "init...")
          (def sendbuf (buffer/new-filled 4096 0xBA))
          (def recvbuf @"")
          (spi/init c 1_000_000)
          (assert (= :ok (:err c)) (spi/err))
          (prin "loopback test...")
          (spi/loopback c true)
          (assert (= :ok (:err c)) (spi/err))
          (spi/readwrite c (length sendbuf) sendbuf recvbuf)
          (assert (= :ok (:err c)) (spi/err))
          (assert (= (length sendbuf) (length recvbuf)))
          (assert (= (memcmp sendbuf recvbuf) 0))
          (print "successful!")

          (assert (:close c))
          (assert (= :ok (:err c)))
          (assert (not (:is-open c)))
          (print "SPI channel successfully closed.")))